name: metabase-app
services:
- name: metabase
  source_dir: /
  github:
    repo: your-username/metabase-deployment
    branch: main
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  envs:
  - key: MB_DB_DBNAME
    value: ${metabase-db.DATABASE}
  - key: MB_DB_USER
    value: ${metabase-db.USERNAME}
  - key: MB_DB_PASS
    value: ${metabase-db.PASSWORD}
  - key: MB_DB_HOST
    value: ${metabase-db.HOSTNAME}
  - key: MB_DB_PORT
    value: ${metabase-db.PORT}
  - key: MB_DB_TYPE
    value: postgres
  - key: JAVA_TOOL_OPTIONS
    value: "-Xmx512m"

databases:
- name: metabase-db
  engine: PG
  version: "15"
  size: basic
  num_nodes: 1